# Generated by Django 4.1.2 on 2022-11-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miappfamilia', '0003_camisas_pantalones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_familia',
            old_name='Sexo',
            new_name='Cargo',
        ),
    ]
